### ISSUE TITLE
Enabled SSL and now it doesn't show the feed count anymore.

### ISSUE THREAD

**Issue by f3bruary** [lamarios/selfoss-companion#4]
I enabled ssl on my server using the new Let's Encrypt service. Now the badge just shows a '!'. I changed the url to https in the settings. And clicking on it still takes me to selfoss. Only the feed count won't show.

Any logs or something I could consult ?

**Comment by lamarios** [comment]
I can't get let's encrypt to work with my server unfortunately... Would you mind giving me your selfoss installation address so i can have a look at it ? You can send it to me at lamarios at gmail ?

**Comment by f3bruary** [comment]
sent

**Comment by lamarios** [comment]
Thanks, let me have a look

**Comment by lamarios** [comment]
I've published a new version that should support auth with username and password. I had issues connecting to your server though, but the short time i've been able to, i faced a cross origin issue, so you have to enable it on your server:

in your .htaccess after enabling the headers mode on your apache server (if running apache)
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
</IfModule>

**Comment by f3bruary** [comment]
yeah I effed something up with let's encrypt. Need some time to fix it. After it's fixed I'll let you know and I'll try what you said out.

**Comment by f3bruary** [comment]
Applied new certs to *.domain.com, and this time it works fine.

**Comment by lamarios** [comment]
Glad that it's working !
