### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by markhaehnel** [lamarios/selfoss-companion#5]
It would be great if you add the ability to authenticate with selfoss if the instance is not public.

**Comment by lamarios** [comment]
Are you using .htacess authentication ? 

If yes you can try to put the URL in the settings as http://username:password@urlofserver 

Sorry for late reply, i replied via email few das ago and it seems like it didn't send through

**Comment by EZTEQ** [comment]
No, i'm using the selfoss integrated userame and password authentication.

**Comment by lamarios** [comment]
Ok, I'll have to look at it. I didn't use selfoss for a very long time and there was no authentication as far as i remember.

**Comment by lamarios** [comment]
I submitted the new version with the authentication handling. It should be available shortly. Feel free to reopen the issue if there's any issue.
